### PR TITLE
Tauri app

### PR DESCRIPTION
**Pull request by fine2006**
Its ready! (partially - only for windows for now, though I haven't tested for MacOS :) )
This took a while, releases are attached if you wanna test.
Need a lil bit help cleaning up the code :)
Also I would love to use the `playlist` branch to make playlists downloadable :D 

Current issue in linux: The app works fine all the way until the download, after which the app thinks the download is done, but it never happened.

### CODE REVIEW

**Comment by fine2006** [comment]
Side note: I want to either make google ads work, or remove the ads message completely :)

**Comment by deepjyoti30** [comment]
@fine2006 I think removing ads would be the way to go, it seems like AdSense is not allowed on desktop apps so it won't be worth the trouble to go for that.

Also, I think rather than merging the source for the desktop app on this repo, we should have a separate repo for that? That would just help to keep things cleared out.

I'll run the build once I'm on my PC. Thanks for the work though!

**Comment by deepjyoti30** [comment]
@fine2006 Can you perhaps share commands on how to build the app locally and how to run it out?!

**Comment by fine2006** [comment]
I actually recommend you to look into my fork and use the binary, its small (and compiled by github actions), and setup on windows is really tough.
Assuming you already have vue-cli setup here.
1. You'll need to install Microsoft Visual Studio C++ build tools. [Download the installer here](https://visualstudio.microsoft.com/visual-cpp-build-tools/), and then run it. When it asks you what packages you would like to install, select C++ Build Tools. (1GB+ of a download)
2. Setup yarn and nvm on windows
3. Install rustup and rust [64-bit Download] (https://win.rustup.rs/x86_64)
4. Install Webview2 on windows [here] (https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)

After this, you have to:
1. Clone the fork
2. get into the project directory
3. in powershell,
```shell
yarn
yarn tauri:serve # for the dev version
yarn tauri:build # for the release version
```

**Comment by fine2006** [comment]
> @fine2006 I think removing ads would be the way to go, it seems like AdSense is not allowed on desktop apps so it won't be worth the trouble to go for that.
> 
> Also, I think rather than merging the source for the desktop app on this repo, we should have a separate repo for that? That would just help to keep things cleared out.
> 
> I'll run the build once I'm on my PC. Thanks for the work though!

I'd think a seperate repo will work great, as I'm looking into adding more features into this, which would set it apart from the desktop app quite a bit (playlist functionality, using tauri's api to make downloads work in mac/linux).
But since this is a learning experience for me (this is my first project on github lol), I can mess things up without knowing it properly, which shouldn't affect the main repo :)

**Comment by deepjyoti30** [comment]
@fine2006 Regarding trying the app, can I not install it on Linux distros? Is it exclusive to Windows?

> I'm looking into adding more features into this, which would set it apart from the desktop app quite a bit (playlist functionality, using tauri's api to make downloads work in mac/linux)

Do you mean you want to add playlist support by using the CLI version of the app? I am already working on a playlist feature for the webapp, just a bit slow because I'm stuck up with a lot of work atm.

> But since this is a learning experience for me (this is my first project on github lol)

Welcome to Open Source!

> I actually recommend you to look into my fork and use the binary, its small (and compiled by github actions), and setup on windows is really tough

Great, the releases look great. I actually didn't see them when I checked the repo earlier. You can make your fork the repo for the desktop app and I can add a link to that on the README once the app is usable by the users!

**Comment by fine2006** [comment]
> Do you mean you want to add playlist support by using the CLI version of the app? I am already working on a playlist feature for the webapp, just a bit slow because I'm stuck up with a lot of work atm.
I absolutely want to use the `playlist` branch :grin:, but I first want to make it work for linux and macos, and would automate it using github actions, as manually compiling isn't an option for me.

You could close this PR, I will try stuff on the fork now :)

**Comment by deepjyoti30** [comment]
@fine2006 Great. Looking forward to the cross platform builds. Do let me know if you need any help regarding GitHub Actions or the ytmdl web API or such.

Also, the `playlist` feature os totally on it's way!

**Pull request closed without merging**
